routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/index', 'Controller');
Route::resource('/home', 'HomeController');
Route::resource('/bees', 'BeeController');
Route::resource('/flowers', 'FlowerController');
Route::resource('/bees/search', 'BeeController');

resources/views/create.blade.php
@extends('templates.template')

@section('content')
<div class="card uper">
  <div class="card-header">
    Adicionar abelha
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br/>
    @endif
      <form method="post" action="{{ route('bees.store') }}">
          <div class="form-group">
              @csrf
              <label for="country_name">Abelha:</label>
              <input type="text" class="form-control" name="name"/>
          </div>
          <div class="form-group">
              <label for="cases">Espécie:</label>
              <input type="text" class="form-control" name="specie"/>
          </div>
          <button type="submit" class="btn btn-primary">Adicionar abelha</button>
      </form>
  </div>
</div>
@endsection

resources/views/createFlower.blade.php
@extends('templates.template')

@section('content')

  <div class="card-header">
    Adicionar flor
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br/>
    @endif
      <form method="post" action="{{ route('flowers.store') }}">
          <div class="form-group">
              @csrf
              <label for="country_name">Nome da flor:</label>
              <input type="text" class="form-control" name="name"/>
          </div>
          <div class="form-group">
              <label for="cases">Breve descrição:</label>
              <input type="text" class="form-control" name="description"/>
          </div>
          <div class="form-group">
              <label for="cases">Mês o qual ela florece:</label>

                <input type="checkbox" name="months[]" value="jan"> Janeiro
                <input type="checkbox" name="months[]" value="fev"> Fevereiro
                <input type="checkbox" name="months[]" value="mar"> Março
                <input type="checkbox" name="months[]" value="abr"> Abril
                <input type="checkbox" name="months[]" value="mai"> Maio
                <input type="checkbox" name="months[]" value="jun"> Junho
                <input type="checkbox" name="months[]" value="jul"> Julho
                <input type="checkbox" name="months[]" value="ago"> Agosto
                <input type="checkbox" name="months[]" value="set"> Setembro
                <input type="checkbox" name="months[]" value="out"> Outubro
                <input type="checkbox" name="months[]" value="nov"> Novembro
                <input type="checkbox" name="months[]" value="dez"> Dezembro

        </div>

        <div class="form-group">
              <label for="cases">Abelhas que polinizam:</label>
              @foreach($bees as $bee)
                    <input type="checkbox" name="bees[]" value="{{$bee->id}}"> {{$bee->name}} </option>
                @endforeach
          </div>

          <button type="submit" class="btn btn-primary">Adicionar flor</button>
      </form>
  </div>

@endsection

resources/views/index.blade.php
@extends('templates.template')
@section('content')
    <h1 class="text-center">Abelhas e flores</h1><hr>
    <div class="text-center mt-3 mb-4">

    <a href="{{url('bees/create')}}">
        <button class="btn btn-success">Cadastrar abelha</button>
    </a>
    <a href="{{url('flowers/create')}}">
        <button class="btn btn-success">Cadastrar flor</button>
    </a>
    <a href="{{url('bees')}}">
        <button class="btn btn-success">Visualizar flor por abelha</button>
    </a>
</div>
@endsection

resources/views/readBee.blade.php
@extends('templates.template')
@section('content')
    <h1 class="text-center">Abelhas e flores</h1><hr>
    <div class="text-center mt-3 mb-4">


    <div class="col-8 m-auto">
        <table class="table text-center">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Nome</th>
                <th scope="col">Descrição</th>
            </tr>
            </thead>
            <tbody>

            <select class="form-control" name="bees">
                @foreach($bees as $bee)
                    <option value="{{$bee->id}}" name="bees">{{$bee->name}}</option>
                @endforeach
            </select><br>
            @foreach ($flowers as $flower)

                    <tr>
                        <th scope="row">{{$flower->name}}</th>
                        <td>{{$flower->description}}</td>
                    </tr>

            @endforeach
            </tbody>
        </table>
    </div>
@endsection